# Generated by Django 5.2.9 on 2025-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0259_add_search_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("bug", "Bug"),
                    ("organization", "Organization"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
