# Generated by Django 5.2.11 on 2026-03-04 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0272_userprofile_leaderboard_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="course",
        ),
        migrations.RemoveField(
            model_name="section",
            name="course",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="section",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="lecturestatus",
            name="lecture",
        ),
        migrations.RemoveField(
            model_name="lecturestatus",
            name="student",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="Lecture",
        ),
        migrations.DeleteModel(
            name="LectureStatus",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
